// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Models
{
    public partial class ForumContext : DbContext
    {
        public ForumContext()
        {
        }

        public ForumContext(DbContextOptions<ForumContext> options)
            : base(options)
        {

        }

        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Topico> Topico { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Comentario>(entity =>
            {
                entity.HasOne(d => d.IdTopicoNavigation)
                    .WithMany(p => p.Comentario)
                    .HasForeignKey(d => d.IdTopico)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_comentario_topico");

                entity.HasOne(d => d.IdUsuNavigation)
                    .WithMany(p => p.Comentario)
                    .HasForeignKey(d => d.IdUsu)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_comentario_usuario");
            });

            modelBuilder.Entity<Topico>(entity =>
            {
                entity.HasOne(d => d.IdUsuNavigation)
                    .WithMany(p => p.Topico)
                    .HasForeignKey(d => d.IdUsu)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_topico_usuario");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}