// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("topico")]
    public partial class Topico
    {
        public Topico()
        {
            Comentario = new HashSet<Comentario>();
            Data = DateTime.Now;
            IdUsu = 1;
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("data", TypeName = "datetime")]
        public DateTime Data { get; set; }
        [Column("dsc")]
        [StringLength(2000)]
        public string Dsc { get; set; }
        [Column("idUsu")]
        public int IdUsu { get; set; }

        [ForeignKey("IdUsu")]
        [InverseProperty("Topico")]
        public virtual Usuario IdUsuNavigation { get; set; }
        [InverseProperty("IdTopicoNavigation")]
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}