// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("usuario")]
    public partial class Usuario
    {
        public Usuario()
        {
            Comentario = new HashSet<Comentario>();
            Topico = new HashSet<Topico>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("nome")]
        [StringLength(200)]
        public string Nome { get; set; }
        [Column("email")]
        [StringLength(200)]
        public string Email { get; set; }
        [Column("foto")]
        public string Foto { get; set; }

        [InverseProperty("IdUsuNavigation")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [InverseProperty("IdUsuNavigation")]
        public virtual ICollection<Topico> Topico { get; set; }
    }
}